spring.datasource.url=${postgresql://postgres:lmDKUoZKBxVnmgxJIZdmiVSZtTwSDMRf@postgres.railway.internal:5432/railway}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
admin.username=admin
admin.password=admin123